repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [
          "--py310-plus"
        ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.7
    hooks:
      - id: prospector
        additional_dependencies:
          - ".[with_everything]"