version: "3.8"

#volumes
volumes:

  postgres_data: { }

services:
  postgres:

    image: postgres:14.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    restart: always
    environment:
      - UTC+2
      - PYTHON UNBUFFERED=1
    depends_on:
      - postgres
    env_file:
      - .env
