from .contact_create_view import ContactCreateView
from .contact_delete_view import ContactDeleteView
from .contact_info_show_view import ContactInfoShowView
from .contact_update_view import ContactUpdateView
